# Generated by Django 4.1.6 on 2024-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="rating",
        ),
        migrations.AddField(
            model_name="dish",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
